<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trains</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/format-page.css">
    <link rel="stylesheet" href="../../css/global-input.css">
    <link rel="stylesheet" href="../../css/employees.css">
    <link rel="stylesheet" href="../../css/tables.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="../../javascript/JQuery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.js"></script>
</head>
<body>
<div id="dashboard-content">
    <div id="header">
        <div class="logo"><a href=""><img src="../../image/logo.png" alt="Logo-license"></a></div>
    </div>

    <div class="close-bar">
        <a class="home">HOME</a>
    </div>

    <div class="container-admin" id="container">
        <div class="left-bar">
            <ul id="nav">
                <li><a class="selected" href="/home">Main Page</a></li>
                <li><a href="/home/buy_ticket">Buy Ticket</a></li>
                <li><a href="/home/employees">Employees</a></li>
                <li><a href="/home/trains">Trains</a></li>
                <li><a href="/home/stations">Stations</a></li>
            </ul>
        </div>
        <div class="content">
            <h1>Employees</h1>
            <p class="sub-title">At this moment you can just delete accounts for students or professors.</p>
            <hr>
            <div class="container-up-add">
                <div id="add-emp">
                    <h3 class="title">Add new employee</h3>
                    <form class="choose-route" style="margin-top: 50px" action="employee/add" method="post">
                        <label for="first-name">First name:</label>
                        <input name="first_name" class="input-g" id="first-name" type="text" required>
                        <label for="last-name">Last name:</label>
                        <input name="last_name" class="input-g" id="last-name" type="text" required>
                        <label for="phone-number">Phone number:</label>
                        <input name="phone" class="input-g" id="phone-number" type="text" required>
                        <label for="choose-job">Select job status:</label>
                        <select name="job" data-placeholder="Select job status..." class="chosen" id="choose-job" required>
                            <option value=""></option>
                            <option value="Controller">Controller</option>
                            <option value="Conductor">Conductor</option>
                        </select>
                        <label for="choose-new-train">Select ID train:</label>
                        <select name="id_train" data-placeholder="Select ID train..." class="chosen" id="choose-new-train" required>
                            <option value=""></option>
                            <?php foreach ($this->data['trains'] as $item)
                            { ?>
                                <option value="<?= $item['id_tren'] ?>"><?= $item['type'] ?>-<?= $item['id_tren'] ?></option>
                            <?php } ?>
                        </select>
                        <div class="error-msg">Error: nu am reusit sa cumpar biletul</div>
                        <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                    </form>
                </div>
                <div id="update-emp">
                    <div class="up-tel-emp">
                        <h3 class="title">Update phone</h3>
                        <form class="choose-route" action="employee/update_phone" method="post">
                            <label for="choose-emp1">Select employee</label>
                            <select data-placeholder="Select employee..." class="chosen" id="choose-emp1" required>
                                <option value=""></option>
                                <?php foreach ($this->data['angajati'] as $item)
                                { ?>
                                    <option value="<?= $item['id_angajat'] ?>"><?= $item['nume_angajat'] ?></option>
                                <?php } ?>
                            </select>
                            <label for="phone">Phone:</label>
                            <input class="input-g" id="phone" type="text" required>
                            <div class="error-msg">Error: 404: update fail!</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                    <div class="up-tr-emp">
                        <h3 class="title">Update ID train</h3>
                        <form class="choose-route"action="employee/update_train" method="post">
                            <label for="choose-emp2">Select employee</label>
                            <select data-placeholder="Select employee..." class="chosen" id="choose-emp2" required>
                                <option value=""></option>
                                <?php foreach ($this->data['angajati'] as $item)
                                { ?>
                                    <option value="<?= $item['id_angajat'] ?>"><?= $item['nume_angajat'] ?></option>
                                <?php } ?>
                            </select>
                            <label for="choose-emp-train">Select train</label>
                            <select data-placeholder="Select ID train..." class="chosen" id="choose-emp-train" required>
                                <option value=""></option>
                                <?php foreach ($this->data['trains'] as $item)
                                { ?>
                                    <option value="<?= $item['id_tren'] ?>"><?= $item['type'] ?>-<?= $item['id_tren'] ?></option>
                                <?php } ?>
                            </select>
                            <div class="error-msg">Error: 404: update fail!</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="table" style="overflow-x:auto;">
                <table>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Train</th>
                        <th>Jobs</th>
                        <th>Option</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->data['angajati'] as $item)
                    { ?>
                        <tr>
                            <td class="column"><?= $item['id_angajat'] ?></td>
                            <td class="column"><?= $item['nume_angajat'] ?></td>
                            <td class="column"><?= $item['phone'] ?></td>
                            <td class="column"><?= $item['tren'] ?></td>
                            <td class="column"><?= $item['job'] ?></td>
                            <td class="column-delete">DELETE</td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>
<script src="../../javascript/responsive-menu.js"></script>
<script src="../../javascript/chosen.js"></script>
<script src="../../javascript/trains.js"></script>
</body>
</html>
