<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rails Company</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/format-page.css">
    <link rel="stylesheet" href="../../css/global-input.css">
    <link rel="stylesheet" href="../../css/index.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="../../javascript/JQuery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.js"></script>
</head>
<body>

<div id="dashboard-content">
    <div id="header">
        <div class="logo"><a href=""><img src="../../image/logo.png" alt="Logo-license"></a></div>
    </div>

    <div class="close-bar">
        <a class="home">HOME</a>
    </div>

    <div class="container-admin" id="container">
        <div class="left-bar">
            <ul id="nav">
                <li><a class="selected" href="/home">Main Page</a></li>
                <li><a href="/home/buy_ticket">Buy Ticket</a></li>
                <li><a href="/home/employees">Employees</a></li>
                <li><a href="/home/trains">Trains</a></li>
                <li><a href="/home/stations">Stations</a></li>
            </ul>
        </div>