<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trains</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/format-page.css">
    <link rel="stylesheet" href="../../css/global-input.css">
    <link rel="stylesheet" href="../../css/stations.css">
    <link rel="stylesheet" href="../../css/tables.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="../../javascript/JQuery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.js"></script>
</head>
<body>
<div id="dashboard-content">
    <div id="header">
        <div class="logo"><a href=""><img src="../../image/logo.png" alt="Logo-license"></a></div>
    </div>

    <div class="close-bar">
        <a class="home">HOME</a>
    </div>

    <div class="container-admin" id="container">
        <div class="left-bar">
            <ul id="nav">
                <li><a class="selected" href="index.phtml">Main Page</a></li>
                <li><a href="buy-ticket.phtml">Buy Ticket</a></li>
                <li><a href="employees.phtml">Employees</a></li>
                <li><a href="trains.phtml">Trains</a></li>
                <li><a href="stations.phtml">Stations</a></li>
            </ul>
        </div>
        <div class="content">
            <h1>Stations & routes</h1>
            <p class="sub-title">You can update, remove or add stations or routes.</p>
            <hr>

            <div class="form-zone">
                <div class="add-zone">
                    <div class="add-routes">
                        <h3 class="title">Add route</h3>
                        <form class="choose-route">
                            <label for="id-train">ID train:</label>
                            <input class="input-g" id="id-train" required>

                            <label for="ch-dep-st">Station departure:</label>
                            <select data-placeholder="Station departure..." class="chosen" id="ch-dep-st" required>
                                <option value=""></option>
                                <?php
                                while ($row = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) {
                                    foreach ($row as $item) {
                                        $value = ($item !== null ? htmlentities($item, ENT_QUOTES) : '&nbsp');
                                        print '<option value= $value >' . $value . '</option>';
                                    }
                                }
                                ?>
                            </select>

                            <label for="time-dep">Hour departure:</label>
                            <input class="input-g" id="time-dep" required>

                            <label for="ch-arr-st">Station arrive:</label>
                            <select data-placeholder="Station arrive..." class="chosen" id="ch-arr-st" required>
                                <option value=""></option>
                                <?php
                                while ($row = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) {
                                    foreach ($row as $item) {
                                        $value = ($item !== null ? htmlentities($item, ENT_QUOTES) : '&nbsp');
                                        print '<option value= $value >' . $value . '</option>';
                                    }
                                }
                                ?>
                            </select>

                            <label for="time-arr">Hour arrival:</label>
                            <input class="input-g" id="time-arr" required>

                            <label for="distance">Distance:</label>
                            <input class="input-g" id="distance" required>

                            <div class="error-msg">Error: nu am reusit sa cumpar biletul</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                    <div class="add-stations">
                        <h3 class="title">Add station</h3>
                        <form class="choose-route">
                            <label for="name-st">Name station:</label>
                            <input class="input-g" id="name-st" required>

                            <label for="wt-time">Waiting time:</label>
                            <input class="input-g" id="wt-time" required>

                            <div class="error-msg">Error: new add fail.</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                </div>
                <div class="update-zone">
                    <div class="update-routes">
                        <h3 class="title">Update route</h3>
                        <form class="choose-route">
                            <label for="ch-up-rt">Id route:</label>
                            <select data-placeholder="Select ID route..." class="chosen" id="ch-up-rt" required>
                                <option value=""></option>
                                <?php
                                while ($row = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) {
                                    foreach ($row as $item) {
                                        $value = ($item !== null ? htmlentities($item, ENT_QUOTES) : '&nbsp');
                                        print '<option value= $value >' . $value . '</option>';
                                    }
                                }
                                ?>
                            </select>

                            <label for="time-up-dep">Hour departure:</label>
                            <input class="input-g" id="time-up-dep" required>

                            <label for="time-up-arr">Hour arrival:</label>
                            <input class="input-g" id="time-up-arr" required>

                            <label for="distance-up">Distance:</label>
                            <input class="input-g" id="distance-up" required>

                            <div class="error-msg">Error: update fail.</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                    <div class="update-stations">
                        <h3 class="title">Update stations</h3>
                        <form class="choose-route">
                            <label for="ch-up-st">Station arrive:</label>
                            <select data-placeholder="Station update..." class="chosen" id="ch-up-st" required>
                                <option value=""></option>
                                <?php
                                while ($row = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) {
                                    foreach ($row as $item) {
                                        $value = ($item !== null ? htmlentities($item, ENT_QUOTES) : '&nbsp');
                                        print '<option value= $value >' . $value . '</option>';
                                    }
                                }
                                ?>
                            </select>
                            <label for="time-up">New-time:</label>
                            <input class="input-g" id="time-up" required>

                            <div class="error-msg">Error: update fail.</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="button-table-select">
                <button class="button-g-table" type="button">Stations</button>
                <button class="button-g-table" type="button">Routes</button>
            </div>
            <div class="table" style="overflow-x:auto; display: block;">
                <table>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name station</th>
                        <th>Waiting time</th>
                        <th>Option</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    while ($row = oci_fetch_array($stid, OCI_RETURN_NULLS + OCI_ASSOC)) {
                        print '<tr>';
                        foreach ($row as $item) {
                            print '<td>' . ($item !== null ? htmlentities($item, ENT_QUOTES) : '&nbsp') . '</td>';
                        }
                        print '<td class="column-delete">DELETE</td>';
                        print '</tr>';
                    }
                    ?>
                    </tbody>
                </table>
                <br>
                <br>
            </div>
            <div class="table" style="overflow-x:auto; display: none;">
                <table>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>ID train</th>
                        <th>Departure</th>
                        <th>Hour departure</th>
                        <th>Arrival</th>
                        <th>Hour arrival</th>
                        <th>Distance</th>
                        <th>Option</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="column">1</td>
                        <td class="column">TR-1834</td>
                        <td class="column">Galati</td>
                        <td class="column">6:40</td>
                        <td class="column">Iasi</td>
                        <td class="column">10:44</td>
                        <td class="column">250</td>
                        <td class="column-delete">DELETE</td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>
<script src="../../javascript/responsive-menu.js"></script>
<script src="../../javascript/chosen.js"></script>
<script src="../../javascript/trains.js"></script>
</body>
</html>
