<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trains</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/format-page.css">
    <link rel="stylesheet" href="../../css/global-input.css">
    <link rel="stylesheet" href="../../css/tables.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="../../javascript/JQuery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.js"></script>
</head>
<body>
<div id="dashboard-content">
    <div id="header">
        <div class="logo"><a href=""><img src="../../image/logo.png" alt="Logo-license"></a></div>
    </div>

    <div class="close-bar">
        <a class="home">HOME</a>
    </div>

    <div class="container-admin" id="container">
        <div class="left-bar">
            <ul id="nav">
                <li><a class="selected" href="/home">Main Page</a></li>
                <li><a href="/home/buy_ticket">Buy Ticket</a></li>
                <li><a href="/home/employees">Employees</a></li>
                <li><a href="/home/trains">Trains</a></li>
                <li><a href="/home/stations">Stations</a></li>
            </ul>
        </div>
        <div class="content">
            <h1>Trains</h1>
            <p class="sub-title">You can update, remove or add train.</p>
            <hr>

            <div class="form-zone">
                <div class="add-zone">
                    <div class="add-trains">
                        <h3 class="title">Add trains</h3>
                        <form class="choose-route">
                            <label for="ch-dep-tr">Station departure:</label>
                            <select data-placeholder="Station departure..." class="chosen" id="ch-dep-tr" required>
                                <option value=""></option>
                                <?php
                                foreach ($this->data['stations'] as $item) {
                                    ?>
                                    <option value="<?= $item['id_statie'] ?>"><?= $item['nume_statie'] ?></option>

                                <?php } ?>
                            </select>

                            <label for="ch-arr-tr">Station arrive:</label>
                            <select data-placeholder="Station arrive..." class="chosen" id="ch-arr-tr" required>
                                <option value=""></option>
                                <?php
                                foreach ($this->data['stations'] as $item) {
                                    ?>
                                    <option value="<?= $item['id_statie'] ?>"><?= $item['nume_statie'] ?></option>

                                <?php } ?>
                            </select>

                            <label for="add-time">Time duration:</label>
                            <input class="input-g" id="add-time" required>

                            <div class="error-msg">Error: nu am reusit sa cumpar biletul</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                    <div class="add-carloads">
                        <h3 class="title">Add carloads</h3>
                        <form class="choose-route">
                            <label for="ch-carload">Id train:</label>
                            <select data-placeholder="Select ID train..." class="chosen" id="ch-carload" required>
                                <option value=""></option>
                                <?php foreach ($this->data['trains'] as $item) { ?>
                                    <option value="<?= $item['id_tren'] ?>"><?= $item['type'] ?>
                                        -<?= $item['id_tren'] ?></option>
                                <?php } ?>
                            </select>

                            <label for="type-car">Type carload:</label>
                            <select data-placeholder="Select class carload..." class="chosen" id="type-car" required>
                                <option value=""></option>
                                <option value="">1</option>
                                <option value="">2</option>
                            </select>

                            <label for="nr-seats">Number of seats:</label>
                            <input class="input-g" id="nr-seats" required type="number">

                            <div class="error-msg">Error: nu am reusit sa cumpar biletul</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                </div>
                <div class="update-zone">
                    <div class="update-status">
                        <h3 class="title">Update status</h3>
                        <form class="choose-route">
                            <label for="ch-carload">Id train:</label>
                            <select data-placeholder="Select ID train..." class="chosen" id="ch-status" required>
                                <option value=""></option>
                                <?php foreach ($this->data['trains'] as $item) { ?>
                                    <option value="<?= $item['id_tren'] ?>"><?= $item['type'] ?>
                                        -<?= $item['id_tren'] ?></option>
                                <?php } ?>
                            </select>

                            <label for="status">Status:</label>
                            <select data-placeholder="Select status train..." class="chosen" id="status" required>
                                <option value=""></option>
                                <option value="">Intarziat</option>
                                <option value="">Fara Intarziere</option>
                            </select>

                            <label for="nr-status">Number of minutes status:</label>
                            <input class="input-g" id="nr-status" required type="number">

                            <div class="error-msg">Error: update fail.</div>
                            <button class="button-g" type="submit" style="margin-left: 195px">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="button-table-select">
                <button class="button-g-table" type="button">Trains</button>
                <button class="button-g-table" type="button">Carloads</button>
            </div>

            <div class="overflow-y" style="overflow: auto; height: 400px; display: block;">
                <div class="table" style="overflow-x:auto;">
                    <table>
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Type</th>
                            <th>Carload</th>
                            <th>Number seats</th>
                            <th>Number employees</th>
                            <th>Status</th>
                            <th>Status time</th>
                            <th>Last station</th>
                            <th>Option</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->data['trains'] as $item) { ?>
                            <tr>
                                <td class="column"><?= $item['id_tren'] ?></td>
                                <td class="column"><?= $item['type'] ?></td>
                                <td class="column"><?= $item['nr_vagoane'] ?></td>
                                <td class="column"><?= $item['nr_locuri'] ?></td>
                                <td class="column"><?= $item['nr_angajati'] ?></td>
                                <td class="column"><?= $item['status'] ?></td>
                                <td class="column"><?= $item['status_time'] ?></td>
                                <td class="column"><?= $item['last_station'] ?></td>
                                <td class="column-delete">DELETE</td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <br>
            <br>
            <div class="overflow-y" style="overflow: auto; height: 400px; display: none;">

            <div class="table" style="overflow-x:auto;">
                <table>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>ID train</th>
                        <th>Class type</th>
                        <th>Number seats</th>
                        <th>Option</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->data['vagoane'] as $item) { ?>
                        <tr>
                            <td class="column"><?= $item['id_vagon'] ?></td>
                            <td class="column"><?= $item['id_tren'] ?></td>
                            <td class="column"><?= $item['clasa'] ?></td>
                            <td class="column"><?= $item['nr_locuri'] ?></td>
                            <td class="column-delete">DELETE</td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
            </div>
            <br>
            <br>
        </div>
    </div>
</div>
<script src="../../javascript/responsive-menu.js"></script>
<script src="../../javascript/chosen.js"></script>
<script src="../../javascript/trains.js"></script>
</body>
</html>
